apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs
  namespace: datainfra-team
spec:
  project: default
  source:
    chart: hello-world
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    helm:
      releaseName: nodejs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: datainfra-testing