apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-2
  namespace: datainfra-team
spec:
  project: default
  source:
    chart: nodejs
    repoURL: https://raw.githubusercontent.com/teroahonen-vungle/kube-sbx/main
    targetRevision: 1.0.0
    helm:
      values: |-
        image:
          repository: teroahonen/nodejs
          tag: latest

      releaseName: nodejs-from-argocd-2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: 04-testing