apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs
  namespace: datainfra-team
spec:
  project: default
  source:
    chart: nodejs
    repoURL: https://raw.githubusercontent.com/teroahonen-vungle/kube-sbx/main
    targetRevision: 0.1.0
    helm:
      values: |-
        image:
          repository: teroahonen/nodejs
          tag: latest

      releaseName: nodejs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: datainfra-testing