apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nodejs
  name: nodejs-with-gitops
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: nodejs
  sessionAffinity: None
  type: ClusterIP