apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
- patch.yml
images:
 - name: teroahonen/nodejs
   newName: teroahonen/nodejs
   newTag: dev
