apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-stage
  namespace: datainfra-team
  labels:
    team: datainfra
spec:
  destination:
    namespace: datainfra-nodejs-stage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: yamls-with-kustomize/nodejs/overlays/stage
    repoURL: 'https://github.com/teroahonen-vungle/kube-sbx.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
