apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-example
  namespace: datainfra-team
  labels:
    team: datainfra
spec:
  destination:
    namespace: datainfra-team
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: helm-with-argocd
    repoURL: 'https://github.com/teroahonen-vungle/kube-sbx.git'
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
